### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by capcrunch12** [drignads/PCS-PREDICTION-MULTI_STRATEGY-BOT#4] opened 2022-01-05 15:53 UTC
Hey drignads,
hope you're well :)

I had already opened an issue but my account got suspended for my username, I think lol.

Just wondering if you could help me, no worries if you can or don't have the time.

Im new(ish) to python and just kind of playing around. 

I replaced your bet logic with Pierre-Antoine's AI bet logic, the bot is running fine, but wont make a buy. I don't think I set up the instance correctly to make a purchase, I was wondering if you could give me some tips? 
This is how I Frankensteined the code:

def makeBet(epoch):
    b = 0.5 #Start balance for RFC Strategy
    bet = 0.05 #Amount of bet
    fee = 0.001 #Transaction fees

    l_b = []
    for i in range(len(Y_test)):
        odd = np.random.randint(1200,3000)/1000
        rand = np.random.randint(0,2)
        if Y_pred[i] == Y_test[i]:
            b += (odd-1)*bet - 2*fee
        else:
            b -= bet - fee

        l_b.append(b)

I appreciate your time, and if this is asking too much no worries, feel free to close the Issue.
Thanks,
Sam

**Comment by drignads** [comment] 2022-01-05 23:32
Hey Sam,  feel free to open an issue anytime :)

It's not placing a bet (purchase), it gives any error? 

I don't know if I got you correctly, but anyways, once you know the position you are going you just call betBear(epoch, value) or betBull(epoch, value).  The value needs to be passed in 'Wei' format, you can use w3.toWei(0.01, 'ether') or w3.fromWei(0.01, 'ether') to convert between

**Comment by capcrunch12** [comment] 2022-01-05 23:43
there is no error, the issue is with the code, I just need to figure out when to place the betBull or the betBear, the AI code is a bit above my station. More learning thanks man :)

**Comment by drignads** [comment] 2022-01-05 23:54
I see.. no problem, Idk if is helpful but if I remember right the AI code will return 1 or 0  (false or true) right? I would add simple if in the end and them call bull or bear for each.   

I use here another function findPostion(epoch).. then I use: 
```python
def makeBet(epoch):
      ...
      position = findPosition(epoch)
      if position == 'bear':
            betBear(epoch, value)

      elif position == 'bull':
            betBull(epoch, value)
```

inside the findPosition I put the nasty stuff hehe

**Comment by capcrunch12** [comment] 2022-01-06 02:17
When I tried it that way, it gave me the error: findposition not defined. Then I tried 
b = 0.5 #Start balance for RFC Strategy
bet = 0.05 #Amount of bet
fee = 0.001 #Transaction fees
value = w3.toWei(0.05, 'ether')


def makeBet(epoch):
    value = w3.toWei(0.05, 'ether')
    for i in range(len(Y_test)):
        odd = np.random.randint(1200,3000)/1000
        rand = np.random.randint(0,2)
    if Y_test == 1:
            betBear(epoch, value)

    elif Y_test == 0:
            betBull(epoch, value)
            
and now its giving me The truth value of an array with more than one element is ambiguous. Use a.any() or a.all(). I appreciate the help but I got a lot more learning to do lol, but the problem solving helps.
Thanks man

**Comment by drignads** [comment] 2022-01-06 22:06
Yep the findPosition is not in the code, just on my machine, that's why the error. 

the way your makeBet looks now, should work. You getting this array issue that basically says the array with more then one element cant be true or false. I think you should select just one of the elements of the array but I'm not sure haha. I'll close the issue since the problem is not related with the bot code itself. Thanks! Feel free to open another one if you need :)

**Comment by capcrunch12** [comment] 2022-01-10 15:52
Hey Man,

Thanks for your previous help.

So I figured it out and rewrote it so I can understand it.
The issue im having now is my transactions keep getting reverted.
Its saying ![image](https://user-images.githubusercontent.com/97181245/148795863-ef9019bf-db74-44d0-a132-54a354d25660.png)

But ive pushed it all the way back to like 40 plus seconds, and its getting 2 block confirmations, I even used my private node to see if it would help, no joy, Any ideas on whats going on here?

**Comment by drignads** [comment] 2022-01-15 21:39
Sup! 
You're running on Windows? I just tested here with 9 sec and is going thru..I'm running on Ubuntu. I suspect is smt related to the datetime format of windows...I can't check rn cause I dont have a windows installed, mb ...

**Comment by capcrunch12** [comment] 2022-01-17 18:39
I am running windows aye

**Comment by drignads** [comment] 2022-01-18 15:08
> I am running windows aye

Yep, it's a datetime/timezone issue. I'm not sure but I believe it solves if you change the line #130 and specify the datetime to timezone UTC.
Soon I'll update the code to fully support windows users

**Comment by ZenkoLab** [comment] 2022-01-30 15:06
> I replaced your bet logic with Pierre-Antoine's AI bet logic, the bot is running fine, but wont make a buy. I don't think I set up the instance correctly to make a purchase, I was wondering if you could give me some tips? This is how I Frankensteined the code:

hey! I was trying to replace his bet logic with Pierre-Antoine'Ai bet logic also! Did you manage to solve the issue? I would love to know

**Comment by drignads** [comment] 2022-02-23 23:17
check new release :)

**Closed by drignads** 2022-02-23 23:17 UTC
